CREATE TABLE IF NOT EXISTS members (
  id BIGINT NOT NULL AUTO_INCREMENT,
  bio VARCHAR(400) NOT NULL,
  displayName VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL,
  username VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_members_email (email),
  UNIQUE KEY uk_members_username (username)
);

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT NOT NULL AUTO_INCREMENT,
  description VARCHAR(400) NOT NULL,
  name VARCHAR(80) NOT NULL,
  owner_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_boards_name (name)
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  content VARCHAR(5000) NOT NULL,
  createdAt DATETIME(6) NOT NULL,
  status ENUM('DRAFT', 'PUBLISHED') NOT NULL,
  title VARCHAR(140) NOT NULL,
  author_id BIGINT NOT NULL,
  board_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post_comments (
  id BIGINT NOT NULL AUTO_INCREMENT,
  body VARCHAR(1000) NOT NULL,
  createdAt DATETIME(6) NOT NULL,
  author_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO members (id, bio, displayName, email, username)
SELECT
  n,
  CONCAT('Seeded member bio ', LPAD(n, 4, '0')),
  CONCAT('Seed Member ', LPAD(n, 4, '0')),
  CONCAT('seed-member-', LPAD(n, 4, '0'), '@example.com'),
  CONCAT('seed-member-', LPAD(n, 4, '0'))
FROM (
  SELECT ones.n + tens.n * 10 + hundreds.n * 100 + 1 AS n
  FROM
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) hundreds
) seq
WHERE n <= 600;

INSERT INTO boards (id, description, name, owner_id)
SELECT
  n,
  CONCAT('Board description ', LPAD(n, 4, '0')),
  CONCAT('seed-board-', LPAD(n, 4, '0')),
  n
FROM (
  SELECT ones.n + tens.n * 10 + hundreds.n * 100 + 1 AS n
  FROM
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) hundreds
) seq
WHERE n <= 600;

INSERT INTO posts (id, content, createdAt, status, title, author_id, board_id)
SELECT
  n,
  CONCAT('Seed post content ', LPAD(n, 4, '0')),
  TIMESTAMP('2026-01-01 00:00:00') + INTERVAL n MINUTE,
  CASE WHEN MOD(n, 3) = 0 THEN 'DRAFT' ELSE 'PUBLISHED' END,
  CONCAT('Seed Post ', LPAD(n, 4, '0')),
  MOD(n - 1, 600) + 1,
  MOD(n - 1, 600) + 1
FROM (
  SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + 1 AS n
  FROM
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1) thousands
) seq
WHERE n <= 1200;

INSERT INTO post_comments (id, body, createdAt, author_id, post_id)
SELECT
  n,
  CONCAT('Seed comment body ', LPAD(n, 4, '0')),
  TIMESTAMP('2026-02-01 00:00:00') + INTERVAL n MINUTE,
  MOD(n - 1, 600) + 1,
  MOD(n - 1, 1200) + 1
FROM (
  SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + 1 AS n
  FROM
    (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2) thousands
) seq
WHERE n <= 2400;

ALTER TABLE members AUTO_INCREMENT = 601;
ALTER TABLE boards AUTO_INCREMENT = 601;
ALTER TABLE posts AUTO_INCREMENT = 1201;
ALTER TABLE post_comments AUTO_INCREMENT = 2401;
